name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi, bro! Thank you for submitting the issue! We will deal with it as soon as possible. Invite you to join our discussion group: 729931395(QQ)"
        pr-message: "Hi, bro! Thank you for submitting the PR! We will deal with it as soon as possible. Invite you to join our discussion group: 729931395(QQ)"
